### ISSUE TITLE
RuntimeError: Device index must not be negative

### ISSUE THREAD

**Issue by YeJinPaark** [lyutyuh/ASP#14]
08/18/2023 05:15:37 - INFO - /mnt/ssd_mnt/pyj/ASP/util/runner.py - Log file path: /mnt/ssd_mnt/pyj/ASP/data/ontonotes_coref/t5_base/log_Aug18_05-15-37.txt
08/18/2023 05:15:37 - INFO - util.tensorize_coref - Loaded tensorized examples from cache: /mnt/ssd_mnt/pyj/ASP/data/ontonotes_coref/cached.tensors.t5-small.2048.bin
/opt/conda/envs/asp/lib/python3.8/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "run_coref.py", line 121, in <module>
    model, _ = runner.initialize_model()
  File "/mnt/ssd_mnt/pyj/ASP/util/runner.py", line 78, in initialize_model
    model = self.model_class_fn(self.config, self.device)
  File "/mnt/ssd_mnt/pyj/ASP/models/model_coref.py", line 49, in __init__
    self.model = T5Coref.from_pretrained(
  File "/opt/conda/envs/asp/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2228, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/mnt/ssd_mnt/pyj/ASP/models/t5_coref.py", line 62, in __init__
    self.action_head = util.make_ffnn(
  File "/mnt/ssd_mnt/pyj/ASP/util/func.py", line 402, in make_ffnn
    ffnn = [make_linear(feat_size, hidden_size[0], std=std), ACT2FN[activation], dropout]
  File "/mnt/ssd_mnt/pyj/ASP/util/func.py", line 385, in make_linear
    linear = nn.Linear(
  File "/opt/conda/envs/asp/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: Device index must not be negative

How can I fix it??

**Comment by 7jun-ui** [comment]
It needs GPU
